# tnain ashxatanq
#
#
name: CI

env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha }}"

on:

  push:
    branches:
     - main

jobs:
  my_test:
   runs-on: ubuntu-latest

   steps:
     - name: Barev_Valodik
       run : echo "Barev_Valodik"

     - name: Exercure few commands
       run: |
         echo "Hello masage1"
         echo "Hello masage2"
         echo "Application name: ${{ env.APPLICATION_NAME }}"

  my_test2:
    runs-on: ubuntu-latest
    needs: [my_test]

    steps:
      - name: Barev_Gugushik
        run: echo "Barev Gugushik"

      - name: Printing_Deployment_Masage
        run: echo "Deploy_pakage name is ${{ env.DEPLOY_PACAGE_NAME }}"