# Home Work tnain ashxatanq

name: hmework
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job_one:

    runs-on: ubuntu-latest

    steps:
    -name: Print hello masage
     run : echo "Hello World"
  


  job_too:
    
    runs-on: ubuntu-latest

    steps:
    -name: Print hello masage
     run : echo "Hello Valodik"
  
