# tnain ashxatanq
#
#
name: CI

env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha }}"

on:

  push:
    branches:
     - main

jobs:
  my_test:
   runs-on: ubuntu-latest

   steps:
     - name: Barev_Valodik
       run : echo "Barev_Valodik"

     - name: Exercure few commands
       run: |
         echo "Hello masage1"
         echo "Hello masage2"
         echo "Application name: ${{ env.APPLICATION_NAME }}"


     - name: List current folder
       run : ls -la

     - name: Git Clone
       uses: actions/checkout@v1

     - name: List current folder
       run : ls -la

  my_test2:
    runs-on: ubuntu-latest
    needs: [my_test]

    steps:
      - name: Barev_Gugushik
        run: echo "Barev Gugushik"

      - name: Printing_Deployment_Masage
        run: echo "Deploy_pakage name is ${{ env.DEPLOY_PACAGE_NAME }}"

      - name: lets test some packages iof the are here 1
        run: aws --version

      - name: lets test some packages iof the are here 2
        run: zip --version


      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
         fromPhoneNumber: '+1(516)9285366'
         toPhoneNumber: '+37494222493'
         message: 'sax lave axpers'
        env:
         TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
         TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
         TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

    

