# Home Work tnain ashxatanq

name: hmework
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  job_1:
    runs-on: ubuntu-latest
    steps:
     - name: Print Hello Valodik
       run: echo "Hello Valodik"
       
 

  job_2:
    runs-on: ubuntu-latest
    steps:
     - name: Print Hello Gugushik
       run : echo "Hello Gugushik"
  
