# 
#
#
name: das



on:

  push:
    branches:
     - main


jobs:
  my_test:
   runs-on: ubuntu-latest

   steps:
     - name: candition
       if:   runner.os == 'Windows'
       run:  echo "Tis operation sistem on the runner is $RUNNER_OS"

     - name: candition 2
       if:   runner.os != 'windows'
       run:  echo "Tis operation sistem is not windows it is $RUNNER_OS"